// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flumeconfig/config.proto

package flumeConfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Agent                []*Agent `protobuf:"bytes,1,rep,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAgent() []*Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

type Agent struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// repeated string sources = 2;
	// repeated string channels = 3;
	// repeated string sinks = 4;
	Sources              *Sources `protobuf:"bytes,5,opt,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{1}
}
func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (dst *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(dst, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetSources() *Sources {
	if m != nil {
		return m.Sources
	}
	return nil
}

type Sources struct {
	Grid                 *Grid         `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	Wapi                 *Wapi         `protobuf:"bytes,2,opt,name=wapi,proto3" json:"wapi,omitempty"`
	Ss                   *SyslogSource `protobuf:"bytes,3,opt,name=ss,proto3" json:"ss,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Sources) Reset()         { *m = Sources{} }
func (m *Sources) String() string { return proto.CompactTextString(m) }
func (*Sources) ProtoMessage()    {}
func (*Sources) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{2}
}
func (m *Sources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sources.Unmarshal(m, b)
}
func (m *Sources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sources.Marshal(b, m, deterministic)
}
func (dst *Sources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sources.Merge(dst, src)
}
func (m *Sources) XXX_Size() int {
	return xxx_messageInfo_Sources.Size(m)
}
func (m *Sources) XXX_DiscardUnknown() {
	xxx_messageInfo_Sources.DiscardUnknown(m)
}

var xxx_messageInfo_Sources proto.InternalMessageInfo

func (m *Sources) GetGrid() *Grid {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *Sources) GetWapi() *Wapi {
	if m != nil {
		return m.Wapi
	}
	return nil
}

func (m *Sources) GetSs() *SyslogSource {
	if m != nil {
		return m.Ss
	}
	return nil
}

type Grid struct {
	Type     string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SpoolDir string   `protobuf:"bytes,2,opt,name=spoolDir,proto3" json:"spoolDir,omitempty"`
	Channels []string `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	// string deletePolicy = 4;
	// Listvalues channels = 5;
	// string deserializer = 6;
	// string fileHeader = 7;
	Interceptors         *Interceptors `protobuf:"bytes,8,opt,name=interceptors,proto3" json:"interceptors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Grid) Reset()         { *m = Grid{} }
func (m *Grid) String() string { return proto.CompactTextString(m) }
func (*Grid) ProtoMessage()    {}
func (*Grid) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{3}
}
func (m *Grid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid.Unmarshal(m, b)
}
func (m *Grid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid.Marshal(b, m, deterministic)
}
func (dst *Grid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid.Merge(dst, src)
}
func (m *Grid) XXX_Size() int {
	return xxx_messageInfo_Grid.Size(m)
}
func (m *Grid) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid.DiscardUnknown(m)
}

var xxx_messageInfo_Grid proto.InternalMessageInfo

func (m *Grid) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Grid) GetSpoolDir() string {
	if m != nil {
		return m.SpoolDir
	}
	return ""
}

func (m *Grid) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *Grid) GetInterceptors() *Interceptors {
	if m != nil {
		return m.Interceptors
	}
	return nil
}

type Wapi struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wapi) Reset()         { *m = Wapi{} }
func (m *Wapi) String() string { return proto.CompactTextString(m) }
func (*Wapi) ProtoMessage()    {}
func (*Wapi) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{4}
}
func (m *Wapi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wapi.Unmarshal(m, b)
}
func (m *Wapi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wapi.Marshal(b, m, deterministic)
}
func (dst *Wapi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wapi.Merge(dst, src)
}
func (m *Wapi) XXX_Size() int {
	return xxx_messageInfo_Wapi.Size(m)
}
func (m *Wapi) XXX_DiscardUnknown() {
	xxx_messageInfo_Wapi.DiscardUnknown(m)
}

var xxx_messageInfo_Wapi proto.InternalMessageInfo

func (m *Wapi) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SyslogSource struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyslogSource) Reset()         { *m = SyslogSource{} }
func (m *SyslogSource) String() string { return proto.CompactTextString(m) }
func (*SyslogSource) ProtoMessage()    {}
func (*SyslogSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{5}
}
func (m *SyslogSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyslogSource.Unmarshal(m, b)
}
func (m *SyslogSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyslogSource.Marshal(b, m, deterministic)
}
func (dst *SyslogSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyslogSource.Merge(dst, src)
}
func (m *SyslogSource) XXX_Size() int {
	return xxx_messageInfo_SyslogSource.Size(m)
}
func (m *SyslogSource) XXX_DiscardUnknown() {
	xxx_messageInfo_SyslogSource.DiscardUnknown(m)
}

var xxx_messageInfo_SyslogSource proto.InternalMessageInfo

func (m *SyslogSource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Interceptors struct {
	Name                 []string     `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Converter            []*Converter `protobuf:"bytes,2,rep,name=converter,proto3" json:"converter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Interceptors) Reset()         { *m = Interceptors{} }
func (m *Interceptors) String() string { return proto.CompactTextString(m) }
func (*Interceptors) ProtoMessage()    {}
func (*Interceptors) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{6}
}
func (m *Interceptors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interceptors.Unmarshal(m, b)
}
func (m *Interceptors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interceptors.Marshal(b, m, deterministic)
}
func (dst *Interceptors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interceptors.Merge(dst, src)
}
func (m *Interceptors) XXX_Size() int {
	return xxx_messageInfo_Interceptors.Size(m)
}
func (m *Interceptors) XXX_DiscardUnknown() {
	xxx_messageInfo_Interceptors.DiscardUnknown(m)
}

var xxx_messageInfo_Interceptors proto.InternalMessageInfo

func (m *Interceptors) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Interceptors) GetConverter() []*Converter {
	if m != nil {
		return m.Converter
	}
	return nil
}

type Selector struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Selector) Reset()         { *m = Selector{} }
func (m *Selector) String() string { return proto.CompactTextString(m) }
func (*Selector) ProtoMessage()    {}
func (*Selector) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{7}
}
func (m *Selector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Selector.Unmarshal(m, b)
}
func (m *Selector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Selector.Marshal(b, m, deterministic)
}
func (dst *Selector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selector.Merge(dst, src)
}
func (m *Selector) XXX_Size() int {
	return xxx_messageInfo_Selector.Size(m)
}
func (m *Selector) XXX_DiscardUnknown() {
	xxx_messageInfo_Selector.DiscardUnknown(m)
}

var xxx_messageInfo_Selector proto.InternalMessageInfo

func (m *Selector) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Converter struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DnsViewDefault       string   `protobuf:"bytes,2,opt,name=dns_view_default,json=dnsViewDefault,proto3" json:"dns_view_default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Converter) Reset()         { *m = Converter{} }
func (m *Converter) String() string { return proto.CompactTextString(m) }
func (*Converter) ProtoMessage()    {}
func (*Converter) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{8}
}
func (m *Converter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Converter.Unmarshal(m, b)
}
func (m *Converter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Converter.Marshal(b, m, deterministic)
}
func (dst *Converter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Converter.Merge(dst, src)
}
func (m *Converter) XXX_Size() int {
	return xxx_messageInfo_Converter.Size(m)
}
func (m *Converter) XXX_DiscardUnknown() {
	xxx_messageInfo_Converter.DiscardUnknown(m)
}

var xxx_messageInfo_Converter proto.InternalMessageInfo

func (m *Converter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Converter) GetDnsViewDefault() string {
	if m != nil {
		return m.DnsViewDefault
	}
	return ""
}

type GetCfg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCfg) Reset()         { *m = GetCfg{} }
func (m *GetCfg) String() string { return proto.CompactTextString(m) }
func (*GetCfg) ProtoMessage()    {}
func (*GetCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_8a3267d69379ba92, []int{9}
}
func (m *GetCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCfg.Unmarshal(m, b)
}
func (m *GetCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCfg.Marshal(b, m, deterministic)
}
func (dst *GetCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCfg.Merge(dst, src)
}
func (m *GetCfg) XXX_Size() int {
	return xxx_messageInfo_GetCfg.Size(m)
}
func (m *GetCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCfg.DiscardUnknown(m)
}

var xxx_messageInfo_GetCfg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Config)(nil), "flumeConfig.Config")
	proto.RegisterType((*Agent)(nil), "flumeConfig.Agent")
	proto.RegisterType((*Sources)(nil), "flumeConfig.Sources")
	proto.RegisterType((*Grid)(nil), "flumeConfig.Grid")
	proto.RegisterType((*Wapi)(nil), "flumeConfig.Wapi")
	proto.RegisterType((*SyslogSource)(nil), "flumeConfig.syslog_source")
	proto.RegisterType((*Interceptors)(nil), "flumeConfig.Interceptors")
	proto.RegisterType((*Selector)(nil), "flumeConfig.Selector")
	proto.RegisterType((*Converter)(nil), "flumeConfig.Converter")
	proto.RegisterType((*GetCfg)(nil), "flumeConfig.GetCfg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlumeConfigClient is the client API for FlumeConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlumeConfigClient interface {
	GetConfig(ctx context.Context, in *GetCfg, opts ...grpc.CallOption) (*Config, error)
	CreateConfig(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Config, error)
}

type flumeConfigClient struct {
	cc *grpc.ClientConn
}

func NewFlumeConfigClient(cc *grpc.ClientConn) FlumeConfigClient {
	return &flumeConfigClient{cc}
}

func (c *flumeConfigClient) GetConfig(ctx context.Context, in *GetCfg, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/flumeConfig.FlumeConfig/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flumeConfigClient) CreateConfig(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/flumeConfig.FlumeConfig/CreateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlumeConfigServer is the server API for FlumeConfig service.
type FlumeConfigServer interface {
	GetConfig(context.Context, *GetCfg) (*Config, error)
	CreateConfig(context.Context, *Config) (*Config, error)
}

func RegisterFlumeConfigServer(s *grpc.Server, srv FlumeConfigServer) {
	s.RegisterService(&_FlumeConfig_serviceDesc, srv)
}

func _FlumeConfig_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCfg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlumeConfigServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flumeConfig.FlumeConfig/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlumeConfigServer).GetConfig(ctx, req.(*GetCfg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlumeConfig_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Config)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlumeConfigServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flumeConfig.FlumeConfig/CreateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlumeConfigServer).CreateConfig(ctx, req.(*Config))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlumeConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flumeConfig.FlumeConfig",
	HandlerType: (*FlumeConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _FlumeConfig_GetConfig_Handler,
		},
		{
			MethodName: "CreateConfig",
			Handler:    _FlumeConfig_CreateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flumeconfig/config.proto",
}

func init() { proto.RegisterFile("flumeconfig/config.proto", fileDescriptor_config_8a3267d69379ba92) }

var fileDescriptor_config_8a3267d69379ba92 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xc7, 0xe9, 0x7c, 0xf7, 0xcc, 0xf8, 0x95, 0x15, 0xa9, 0x45, 0x64, 0x88, 0x08, 0x65, 0x2f,
	0x66, 0xa0, 0x7a, 0x25, 0x78, 0x21, 0xb3, 0xec, 0xb2, 0xe8, 0x55, 0x16, 0xd4, 0xbb, 0x21, 0xb6,
	0xa7, 0x35, 0xd0, 0x4d, 0x4a, 0x92, 0xd9, 0x61, 0x6f, 0xf5, 0x09, 0xc4, 0x47, 0xf0, 0x91, 0x7c,
	0x05, 0x1f, 0x44, 0x92, 0xce, 0xcc, 0x4e, 0x97, 0x5e, 0x35, 0x27, 0xff, 0x5f, 0xfe, 0xe7, 0x9c,
	0xa4, 0x07, 0xa2, 0xa2, 0xda, 0x5c, 0x63, 0xa6, 0x64, 0x21, 0xca, 0x65, 0xf3, 0x59, 0xd4, 0x5a,
	0x59, 0x45, 0xa6, 0x5e, 0x59, 0xf9, 0xad, 0xf8, 0x45, 0xa9, 0x54, 0x59, 0xe1, 0x92, 0xd7, 0x62,
	0xc9, 0xa5, 0x54, 0x96, 0x5b, 0xa1, 0xa4, 0x69, 0x50, 0x9a, 0xc2, 0xa8, 0xe1, 0x48, 0x02, 0x43,
	0x5e, 0xa2, 0xb4, 0x51, 0x30, 0xef, 0x27, 0xd3, 0x94, 0x2c, 0x8e, 0x4c, 0x16, 0x1f, 0x9c, 0xc2,
	0x1a, 0x80, 0x7e, 0x84, 0xa1, 0x8f, 0x09, 0x81, 0x81, 0xe4, 0xd7, 0x18, 0x05, 0xf3, 0x20, 0x09,
	0x99, 0x5f, 0x93, 0x05, 0x8c, 0x8d, 0xda, 0xe8, 0x0c, 0x4d, 0x34, 0x9c, 0x07, 0xc9, 0x34, 0x7d,
	0xda, 0x32, 0xba, 0x6a, 0x34, 0xb6, 0x87, 0xe8, 0xcf, 0x00, 0xc6, 0xbb, 0x4d, 0xf2, 0x1a, 0x06,
	0xa5, 0x16, 0xb9, 0xf7, 0x9b, 0xa6, 0x4f, 0x5a, 0x07, 0x2f, 0xb4, 0xc8, 0x99, 0x97, 0x1d, 0xb6,
	0xe5, 0xb5, 0x88, 0x7a, 0x1d, 0xd8, 0x17, 0x5e, 0x0b, 0xe6, 0x65, 0x72, 0x0a, 0x3d, 0x63, 0xa2,
	0xbe, 0x87, 0xe2, 0x16, 0x64, 0x6e, 0x4d, 0xa5, 0xca, 0x75, 0x53, 0x02, 0xeb, 0x19, 0x43, 0x7f,
	0x05, 0x30, 0x70, 0x19, 0x5c, 0x4b, 0xf6, 0xb6, 0x3e, 0xb4, 0xe4, 0xd6, 0x24, 0x86, 0x89, 0xa9,
	0x95, 0xaa, 0xce, 0x84, 0xf6, 0x39, 0x43, 0x76, 0x88, 0x9d, 0x96, 0x7d, 0xe7, 0x52, 0x62, 0xe5,
	0x52, 0xf5, 0x9d, 0xb6, 0x8f, 0xc9, 0x7b, 0x98, 0x09, 0x69, 0x51, 0x67, 0x58, 0x5b, 0xa5, 0x4d,
	0x34, 0xf1, 0xa5, 0x3c, 0x6f, 0x95, 0x72, 0x79, 0x04, 0xb0, 0x16, 0x4e, 0x63, 0x18, 0xb8, 0x6e,
	0xba, 0x4a, 0xa2, 0xaf, 0xe0, 0x41, 0xab, 0x89, 0x4e, 0xe8, 0x2b, 0xcc, 0x8e, 0xed, 0x8f, 0x9e,
	0xab, 0x7f, 0x78, 0xae, 0xb7, 0x10, 0x66, 0x4a, 0xde, 0xa0, 0xb6, 0xe8, 0x9a, 0x73, 0x2f, 0xff,
	0xac, 0x55, 0xe0, 0x6a, 0xaf, 0xb2, 0x3b, 0x90, 0xbe, 0x84, 0xc9, 0x15, 0x56, 0x98, 0x59, 0xa5,
	0x3b, 0x33, 0x5f, 0x42, 0x78, 0x38, 0xd7, 0x79, 0xa5, 0x09, 0x3c, 0xce, 0xa5, 0x59, 0xdf, 0x08,
	0xdc, 0xae, 0x73, 0x2c, 0xf8, 0xa6, 0xb2, 0xbb, 0xab, 0x7d, 0x98, 0x4b, 0xf3, 0x59, 0xe0, 0xf6,
	0xac, 0xd9, 0xa5, 0x13, 0x18, 0x5d, 0xa0, 0x5d, 0x15, 0x65, 0xfa, 0x27, 0x80, 0xe9, 0xf9, 0x5d,
	0x65, 0xe4, 0x1c, 0x42, 0xa7, 0x34, 0xc1, 0x49, 0xfb, 0x67, 0xf1, 0x27, 0xe2, 0x93, 0xfb, 0x9d,
	0x14, 0xa2, 0xa4, 0x8f, 0x7e, 0xfc, 0xfd, 0xf7, 0xbb, 0x17, 0x92, 0xf1, 0x6e, 0x66, 0xc8, 0x27,
	0x98, 0xad, 0x34, 0x72, 0x8b, 0x9d, 0x56, 0xbb, 0x29, 0xea, 0xb4, 0x22, 0xde, 0x6a, 0x46, 0xf7,
	0x56, 0xef, 0x82, 0xd3, 0x6f, 0x23, 0x3f, 0x57, 0x6f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0xdd, 0xb0, 0xdb, 0x9e, 0x03, 0x00, 0x00,
}
